1. [SCNAction](../SCNAction_Class/index.html#//apple_ref/occ/cl/SCNAction) An <code class="code-voice">SCNAction</code> object is an action that is executed by a node (<code class="code-voice">SCNNode</code>).
1. [SCNAnimationEvent](../SCNAnimationEvent_Class/index.html#//apple_ref/occ/cl/SCNAnimationEvent) You attach an <code class="code-voice">SCNAnimationEvent</code> object to an animation to execute a block at a specific time when the animation plays.
1. [SCNCamera](../SCNCamera_Class/index.html#//apple_ref/occ/cl/SCNCamera) An <code class="code-voice">SCNCamera</code> object manages camera attributes attached to a node.
1. [SCNConstraint](../SCNConstraint_Class/index.html#//apple_ref/occ/cl/SCNConstraint) A constraint automatically adjusts the transformation (position, rotation, and scale) of a node based on rules you define.
1. [SCNIKConstraint](../SCNIKConstraint_Class/index.html#//apple_ref/occ/cl/SCNIKConstraint) An <code class="code-voice">SCNIKConstraint</code> object automatically adjusts the orientations of one or more nodes in a specified hierarchy, applying inverse kinematics to make the chain reach toward a target point.
1. [SCNLookAtConstraint](../SCNLookAtConstraint_Class/index.html#//apple_ref/occ/cl/SCNLookAtConstraint) An <code class="code-voice">SCNLookAtConstraint</code> object automatically adjusts a node’s orientation so that it always points toward another node.
1. [SCNTransformConstraint](../SCNTransformConstraint_Class/index.html#//apple_ref/occ/cl/SCNTransformConstraint) An <code class="code-voice">SCNTransformConstraint</code> object runs a block that you specify to compute a new transformation (position, rotation, and scale) for each node affected by the constraint.
1. [SCNGeometry](../SCNGeometry_Class/index.html#//apple_ref/occ/cl/SCNGeometry) An <code class="code-voice">SCNGeometry</code> object represents a three-dimensional shape—a collection of vertices, normals and texture coordinates that define a surface, also known as a model or mesh.
1. [SCNBox](../SCNBox_Class/index.html#//apple_ref/occ/cl/SCNBox) An <code class="code-voice">SCNBox</code> geometry models a six-sided polyhedron whose faces are all rectangles.
1. [SCNCapsule](../SCNCapsule_Class/index.html#//apple_ref/occ/cl/SCNCapsule) An <code class="code-voice">SCNCapsule</code> geometry models a right circular cylinder whose ends are capped with hemispheres.
1. [SCNCone](../SCNCone_Class/index.html#//apple_ref/occ/cl/SCNCone) An <code class="code-voice">SCNCone</code> geometry models a right circular cone or frustum.
1. [SCNCylinder](../SCNCylinder_Class/index.html#//apple_ref/occ/cl/SCNCylinder) An <code class="code-voice">SCNCylinder</code> geometry models a right circular cylinder.
1. [SCNFloor](../SCNFloor_Class/index.html#//apple_ref/occ/cl/SCNFloor) An <code class="code-voice">SCNFloor</code> geometry models an infinite plane.
1. [SCNPlane](../SCNPlane_Class/index.html#//apple_ref/occ/cl/SCNPlane) An <code class="code-voice">SCNPlane</code> geometry models a rectangular, one-sided plane of specified width and height.
1. [SCNPyramid](../SCNPyramid_Class/index.html#//apple_ref/occ/cl/SCNPyramid) An <code class="code-voice">SCNPyramid</code> geometry models a right rectangular pyramid.
1. [SCNShape](../SCNShape_Class/index.html#//apple_ref/occ/cl/SCNShape) An <code class="code-voice">SCNShape</code> object is geometry that creates its contents from a two-dimensional path, optionally extruded to create a three-dimensional object.
1. [SCNSphere](../SCNSphere_Class/index.html#//apple_ref/occ/cl/SCNSphere) An <code class="code-voice">SCNSphere</code> geometry models a sphere (also known as a ball or globe).
1. [SCNText](../SCNText_Class/index.html#//apple_ref/occ/cl/SCNText) An <code class="code-voice">SCNText</code> object is a geometry that creates its contents from a string of text, rendered in 2D and optionally extruded to create a three-dimensional object.
1. [SCNTorus](../SCNTorus_Class/index.html#//apple_ref/occ/cl/SCNTorus) An <code class="code-voice">SCNTorus</code> geometry models a ring-shaped object.
1. [SCNTube](../SCNTube_Class/index.html#//apple_ref/occ/cl/SCNTube) An <code class="code-voice">SCNTube</code> geometry models a tube or pipe—a right circular cylinder with a circular hole along its central axis.
1. [SCNGeometryElement](../SCNGeometryElement_Class/index.html#//apple_ref/occ/cl/SCNGeometryElement) An <code class="code-voice">SCNGeometryElement</code> object describes how vertices are connected to form the surface of a three-dimensional object, or geometry.
1. [SCNGeometrySource](../SCNGeometrySource_Class/index.html#//apple_ref/occ/cl/SCNGeometrySource) An <code class="code-voice">SCNGeometrySource</code> object specifies per-vertex data for the set of vertices forming the surface of a three-dimensional object, or geometry.
1. [SCNHitTestResult](../SCNHitTestResult_Class/index.html#//apple_ref/occ/cl/SCNHitTestResult) Hit-testing is the process of finding elements of a scene located at a specified point, or along a specified line segment (or ray).
1. [SCNLevelOfDetail](../SCNLevelOfDetail_Class/index.html#//apple_ref/occ/cl/SCNLevelOfDetail) Use <code class="code-voice">SCNLevelOfDetail</code> objects to enable automatic substitution of alternate levels of detail for a geometry.
1. [SCNLight](../SCNLight_Class/index.html#//apple_ref/occ/cl/SCNLight) An <code class="code-voice">SCNLight</code> object represents a light source.
1. [SCNMaterial](../SCNMaterial_Class/index.html#//apple_ref/occ/cl/SCNMaterial) An <code class="code-voice">SCNMaterial</code> object manages the lighting and shading attributes associated with the surface of a geometry that define its appearance when rendered.
1. [SCNMaterialProperty](../SCNMaterialProperty_Class/index.html#//apple_ref/occ/cl/SCNMaterialProperty) An <code class="code-voice">SCNMaterialProperty</code> object represents the contents—color, texture, or other visual elements—of one of a material’s visual properties.
1. [SCNMorpher](../SCNMorpher_Class/index.html#//apple_ref/occ/cl/SCNMorpher) An <code class="code-voice">SCNMorpher</code> object deforms the surface of a node’s geometry, smoothly transitioning between a base geometry and one or more target geometries.
1. [SCNNode](../SCNNode_Class/index.html#//apple_ref/occ/cl/SCNNode) An <code class="code-voice">SCNNode</code> object represents a portion of a scene graph.
1. [SCNParticlePropertyController](../SCNParticlePropertyController_Class/index.html#//apple_ref/occ/cl/SCNParticlePropertyController) An <code class="code-voice">SCNParticlePropertyController</code> object uses Core Animation semantics to animate a property of the particles rendered by an <code class="code-voice">SCNParticleSystem</code> object.
1. [SCNParticleSystem](../SCNParticleSystem_Class/index.html#//apple_ref/occ/cl/SCNParticleSystem) An <code class="code-voice">SCNParticleSystem</code> object automatically creates, animates, and renders a system of particles—small image sprites—according to a high-level simulation whose general behavior you specify.
1. [SCNPhysicsBehavior](../SCNPhysicsBehavior/index.html#//apple_ref/occ/cl/SCNPhysicsBehavior) An <code class="code-voice">SCNPhysicsBehavior</code> object defines a high-level behavior for one or more physics bodies, modifying the results of the physics simulation.
1. [SCNPhysicsBallSocketJoint](../SCNPhysicsBallSocketJoint_Class/index.html#//apple_ref/occ/cl/SCNPhysicsBallSocketJoint) An <code class="code-voice">SCNPhysicsBallSocketJoint</code> is a behavior that connects two physics bodies and allows them to pivot around each other in any direction.
1. [SCNPhysicsHingeJoint](../SCNPhysicsHingeJoint_Class/index.html#//apple_ref/occ/cl/SCNPhysicsHingeJoint) An <code class="code-voice">SCNPhysicsHingeJoint</code> is a behavior that connects two physics bodies and allows them to pivot around each other on a single axis.
1. [SCNPhysicsSliderJoint](../SCNPhysicsSliderJoint_Class/index.html#//apple_ref/occ/cl/SCNPhysicsSliderJoint) An <code class="code-voice">SCNPhysicsSliderJoint</code> is a behavior that connects two physics bodies and allows them to slide against each other and rotate around their connecting points.
1. [SCNPhysicsVehicle](../SCNPhysicsVehicle_Class/index.html#//apple_ref/occ/cl/SCNPhysicsVehicle) An <code class="code-voice">SCNPhysicsVehicle</code> object modifies SceneKit’s simulation of a physics body so that it behaves like a car, motorcycle, or other wheeled vehicle.
1. [SCNPhysicsBody](../SCNPhysicsBody_Class/index.html#//apple_ref/occ/cl/SCNPhysicsBody) An <code class="code-voice">SCNPhysicsBody</code> object is used to add physics simulation to a node.
1. [SCNPhysicsContact](../SCNPhysicsContact_Class/index.html#//apple_ref/occ/cl/SCNPhysicsContact) An <code class="code-voice">SCNPhysicsContact</code> object describes a contact between two physics bodies in your scene’s physics simulation.
1. [SCNPhysicsField](../SCNPhysicsField_Class/index.html#//apple_ref/occ/cl/SCNPhysicsField) An <code class="code-voice">SCNPhysicsField</code> object applies forces to objects in an area of effect within a scene.
1. [SCNPhysicsShape](../SCNPhysicsShape_Class/index.html#//apple_ref/occ/cl/SCNPhysicsShape) An <code class="code-voice">SCNPhysicsShape</code> object simulates the solid volume associated with an <code class="code-voice">SCNPhysicsBody</code> object for use in collision detection.
1. [SCNPhysicsVehicleWheel](../SCNPhysicsVehicleWheel_Class/index.html#//apple_ref/occ/cl/SCNPhysicsVehicleWheel) An <code class="code-voice">SCNPhysicsVehicleWheel</code> object defines the appearance and physical characteristics of an individual wheel associated with an <code class="code-voice">SCNPhysicsVehicle</code> behavior.
1. [SCNPhysicsWorld](../SCNPhysicsWorld_Class/index.html#//apple_ref/occ/cl/SCNPhysicsWorld) An <code class="code-voice">SCNPhysicsWorld</code> object simulates collisions and other physical properties in a scene.
1. [SCNProgram](../SCNProgram_Class/index.html#//apple_ref/occ/cl/SCNProgram) You use an <code class="code-voice">SCNProgram</code> object to perform custom rendering using shader programs written in the OpenGL Shading Language (GLSL).
1. [SCNRenderer](../SCNRenderer_Class/index.html#//apple_ref/occ/cl/SCNRenderer) An <code class="code-voice">SCNRenderer</code> object renders a SceneKit scene into an arbitrary OpenGL context.
1. [SCNScene](../SCNScene_Class/index.html#//apple_ref/occ/cl/SCNScene) An <code class="code-voice">SCNScene</code> object represents a three-dimensional scene.
1. [SCNSceneSource](../SCNSceneSource_Class/index.html#//apple_ref/occ/cl/SCNSceneSource) An <code class="code-voice">SCNSceneSource</code> object manages the data-reading tasks associated with loading scene contents from a file (or <code class="code-voice">NSData</code> object).
1. [SCNSkinner](../SCNSkinner_Class/index.html#//apple_ref/occ/cl/SCNSkinner) An <code class="code-voice">SCNSkinner</code> object provides access to portions of a node hierarchy used for skeletal animation.
1. [SCNTechnique](../SCNTechnique_Class/index.html#//apple_ref/occ/cl/SCNTechnique) An <code class="code-voice">SCNTechnique</code> object describes a rendering technique that uses one or more additional drawing passes, each of which uses a custom OpenGL shader program to augment or postprocess SceneKit’s rendering of the scene.
1. [SCNTransaction](../SCNTransaction_Class/index.html#//apple_ref/occ/cl/SCNTransaction) The <code class="code-voice">SCNTransaction</code> class defines SceneKit’s mechanism for batching scene graph modifications into atomic updates.
1. [NSView](../../../Java/Reference/JNFRunnableClassRef/index.html#//apple_ref/occ/cl/NSView) The <code class="code-voice">NSView</code> class defines the basic drawing, event-handling, and printing architecture of an app.
1. [SCNView](../SCNView_Class/index.html#//apple_ref/occ/cl/SCNView) You use an <code class="code-voice">SCNView</code> object to render SceneKit content for display in your app.
1. [CAOpenGLLayer](../../../GraphicsImaging/Reference/CAOpenGLLayer_class/index.html#//apple_ref/occ/cl/CAOpenGLLayer) <code class="code-voice">CAOpenGLLayer</code> provides a layer suitable for rendering OpenGL content.
1. [SCNLayer](../SCNLayer_Class/index.html#//apple_ref/occ/cl/SCNLayer) An <code class="code-voice">SCNLayer</code> object is a Core Animation layer that renders a SceneKit scene as its content.
